platform :ios, "7.0"
pod 'CocoaLumberjack'
pod "MBXMapKit"
pod "CZWeatherKit"
pod 'UIActionSheet+Blocks'
pod 'ionicons'
pod 'SMCalloutView'

# target "Ride" do
# 
# end
# 
# target "RideTests" do
# 
# end

