platform :ios, '8.0'
use_frameworks!

def shared_pods
    pod 'ECSlidingViewController', '~> 2.0.3'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'KeychainAccess'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'OAuthSwift'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
#    pod 'Mapbox-iOS-SDK', :configurations => ['Release']
    pod 'Mapbox-iOS-SDK-symbols', :podspec => "https://raw.githubusercontent.com/mapbox/mapbox-gl-native/master/platform/ios/Mapbox-iOS-SDK-symbols.podspec", :configurations => ['Debug']
    pod 'MapboxStatic.swift', :git => "https://github.com/mapbox/MapboxStatic.swift.git"
    pod 'Mixpanel'
    pod 'CocoaLumberjack/Swift'
    pod 'GzipSwift'
    pod 'Kingfisher'
    pod 'Charts'
    pod 'Presentr'
end

target 'Ride Report' do
    shared_pods
end

target 'Ride Report Tests' do
    shared_pods
    pod 'OHHTTPStubs/Swift'
end

target 'Ride Report UITests' do
    shared_pods
    pod 'OHHTTPStubs/Swift'
end

target 'Motion' do
    shared_pods
    pod 'Eureka'
end

target 'Ride Report Notification Content' do
    pod 'SwiftyJSON'
    pod 'GzipSwift'
    pod 'CocoaLumberjack/Swift'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'Ride Report Dev'
        end
    end
end
