platform :ios, '8.0'
use_frameworks!

target 'Ride Report' do
    pod 'ECSlidingViewController', '~> 2.0.3'
    pod 'UIActionSheet+Blocks'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'KeychainAccess'
    pod 'Alamofire', '~> 3.0'
    pod 'OAuthSwift'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'Mapbox-iOS-SDK'
    pod 'PNChart',:path => '../Submodules/PNChart'
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
    pod 'Mixpanel'
    pod 'SwiftyJSON'
    pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'swift_2.0'
    pod 'OpenCV'
end

target 'Motion' do
    pod 'SwiftChart'
    pod 'SwiftyJSON'
    pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', :branch => 'swift_2.0'
    pod 'OpenCV'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
