_prefs: 
  mapid: quicklywilliam.3939fb5f
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 15.293
  - 50.8476
  - 4
description: Ride's version of Dark
format: "png8:m=h"
interactivity_layer: ''
layers: 
  - landcover
  - landuse
  - hillshade
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - country_label_line
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
maxzoom: 22
minzoom: 0
name: Ride Dark v0.1
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - labels.mss
  - roads.mss
  - terrain.mss
template: ''
